$testobject {

	$testcase 1 {
		$name ""
		$uuid "96a66226-ce48-48b2-8614-9c54f463bcb3"

		$teststep 1.1 {
			$name ""
			$uuid "997bdf6f-5907-4aea-88b7-e0db12222c51"
			$inputs {
				a = 2
				b = 3
				c = 5
			}
			$outputs {
				c = 5
				return 5
			}
			$calltrace {
				*** Ignore Call Trace ***
			}
		}
	}

	$testcase 2 {
		$name ""
		$uuid "63b2f29e-f72d-4788-8dce-24554e65828e"

		$teststep 2.1 {
			$name ""
			$uuid "1d62a752-ae6b-4f53-8884-37fe0c5f23da"
			$inputs {
				a = 4
				b = 5
				c = 9
			}
			$outputs {
				c = 9
				return 9
			}
			$calltrace {
				*** Ignore Call Trace ***
			}
		}
	}
}