$testobject {

	$testcase 1 {
		$name ""
		$uuid "67937b92-879b-4ae2-b0d0-6f4fe8bd97cf"

		$teststep 1.1 {
			$name ""
			$uuid "d19b84c7-ce53-40c8-97c6-04461c22bb9e"
			$inputs {
				a = 2
				b = 3
				c = 5
			}
			$outputs {
				c = 5
				return 5
			}
			$calltrace {
				*** Ignore Call Trace ***
			}
		}
	}

	$testcase 2 {
		$name ""
		$uuid "53be40e2-8389-44a5-aaf8-d2f5070ace1a"

		$teststep 2.1 {
			$name ""
			$uuid "785e2b62-e209-4a67-b5f2-f3de742047bb"
			$inputs {
				a = 4
				b = 5
				c = 9
			}
			$outputs {
				c = 9
				return 9
			}
			$calltrace {
				*** Ignore Call Trace ***
			}
		}
	}
}